### ISSUE TITLE
前端只发送一次请求，http-mock打印了一堆日志，然后报错了

### ISSUE THREAD

**Issue by rbsrcy** [hbxeagle/http-mock-json-server#1]
Proxy to 127.0.0.1:3000
REQ: http://127.0.0.1:3000/queryProductTargetUrl
Proxy to 127.0.0.1:3000
REQ: http://127.0.0.1:3000/queryProductTargetUrl
Proxy to 127.0.0.1:3000
REQ: http://127.0.0.1:3000/queryProductTargetUrl
Proxy to 127.0.0.1:3000
REQ: http://127.0.0.1:3000/queryProductTargetUrl
Proxy to 127.0.0.1:3000
REQ: http://127.0.0.1:3000/queryProductTargetUrl
Proxy to 127.0.0.1:3000
REQ: http://127.0.0.1:3000/queryProductTargetUrl
Proxy to 127.0.0.1:3000
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: connect EADDRNOTAVAIL 127.0.0.1:3000 - Local (0.0.0.0:0)
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at internalConnect (net.js:889:16)
    at lookupAndConnect (net.js:977:5)
    at Socket.realConnect (net.js:945:5)
    at Agent.connect [as createConnection] (net.js:77:22)
    at Agent.createSocket (_http_agent.js:195:26)
    at Agent.addRequest (_http_agent.js:157:10)

**Comment by hbxeagle** [comment]
方便发一下mock的配置文件吗？
